baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/#top"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/#publications"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 3

  [[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 4

