name: Build site with hugo
run-name: ${{ github.actor }} triggered run
on:
  workflow_call:

jobs:
  hugo-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'

      - name: Build site
        run: hugo --minify
      
      - name: Add artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: docs

